# Copyright 2024 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Build and release packages

on:
  workflow_dispatch:
  schedule:
    # Runs at 05:00 AM UTC, which is 9:00 PM PST (UTC-8) / 10:00 PM PDT (UTC-7)
    # This lines up with https://github.com/iree-org/iree/blob/main/.github/workflows/schedule_candidate_release.yml
    # Downstream projects using nightly releases should expect IREE and
    # wave packages to all be available around the same time. This
    # build is much faster than the IREE build though.
    - cron: '0 5 * * *'

jobs:
  build_packages:
    if: ${{ github.repository_owner == 'iree-org' || github.event_name != 'schedule' }}
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: write
    env:
      OUTPUT_DIR: "${{ github.workspace }}/bindist"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux packages
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp310
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp311
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp312
            platform: manylinux_x86_64
          - runs-on: ubuntu-24.04
            package: wave-lang
            python-version: cp313
            platform: manylinux_x86_64

          # Windows packages.
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp310
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp311
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp312
            platform: win_amd64
          - runs-on: windows-2025
            package: wave-lang
            python-version: cp313
            platform: win_amd64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build wheels
        uses: pypa/cibuildwheel@352e01339f0a173aa2a3eb57f01492e341e83865 # v3.1.3
        env:
          CIBW_BUILD: ${{ matrix.python-version }}-${{ matrix.platform }}
          CIBW_BEFORE_ALL_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
          CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"

      - name: Upload python wheels
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          if-no-files-found: error
          name: snapshot-${{ matrix.package }}-${{ matrix.python-version }}-${{ matrix.platform }}
          path: ./wheelhouse/*.whl

  release_packages:
    needs: build_packages
    if: ${{ success() && (github.repository_owner == 'iree-org' || github.event_name != 'schedule') }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Create/update a release
    steps:
      - name: Download wheels
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: snapshot-*
          # Merge all artifacts into a single directory
          merge-multiple: true
          path: dist

      - name: Release python wheels
        uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af # v1.18.0
        with:
          artifacts: dist/*.whl
          tag: "dev-wheels"
          name: "dev-wheels"
          body: "Automatic nightly release of wave-lang python wheels."
          removeArtifacts: true
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: false
