name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
        build_run_id:
            description: Run ID to retrieve Python wheels from
            required: true

jobs:
  pypi-publish:
    name: Publish run ${{ github.event.inputs.build_run_id }}'s wheels to PyPI
    runs-on: ubuntu-24.04
    environment:
        name: pypi-publish
        url: https://pypi.org/project/wave-lang/
    permissions:
      id-token: write
    steps:
      - name: Download wheels
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          run-id: ${{ github.event.inputs.build_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: snapshot-*
          merge-multiple: true
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v.1.13.0
